# Generated by Django 4.0.3 on 2022-04-10 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userurl',
            name='uniqueId',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=20, unique=True),
        ),
    ]
