# Generated by Django 4.0.3 on 2022-04-10 13:40

from django.db import migrations, models
import urlshortner.models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0002_alter_userurl_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userurl',
            name='uniqueId',
            field=models.CharField(blank=True, default=urlshortner.models.id_gen, editable=False, max_length=20, unique=True),
        ),
    ]
